<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Spatial Map</title>
    <style>
        body {
            font-family: 'Times New Roman', Times, serif;
            margin: 150px 20px 30px 20px;
        }

        @page {
            margin: 100px 30px;
            /* Top and Bottom margins leave space for header/footer */
        }

        header {
            position: fixed;
            top: -80px;
            /* Adjust position based on your header height */
            left: 0;
            right: 0;
            height: 80px;
            text-align: center;
            line-height: 1.5;
        }

        .map-container {
            position: relative;
            width: 100%;
            height: 500px;
            overflow: hidden;
            text-align: center;
        }

        .map-image {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            max-width: 100%;
            max-height: 100%;
            object-fit: cover;
        }

        footer {
            position: fixed;
            bottom: -50px;
            /* Adjust position based on your footer height */
            left: 0;
            right: 0;
            height: 50px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }

        .footer-page {
            position: absolute;
            right: 0;
            bottom: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 14px;
        }

        table,
        th,
        td {
            border: 1px solid black;
        }

        th,
        td {
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #e6e6e6;
            text-transform: uppercase;
            font-size: 12px;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tr:nth-child(odd) {
            background-color: #fff;
        }
    </style>
</head>

<body>
    <header>
        <img src="{{ public_path('cenrologo.jpg') }}" alt="Government Logo" style="height: 100px;">
        <h1>Spatial Map</h1>
        <p>Generated by the WMMNS</p>
        <p>Date: {{ \Carbon\Carbon::now()->format('F d, Y') }}</p>
    </header>
    <footer>
        <p>Certified by the CENRO SANTIAGO CITY</p>
        <p>&copy; {{ \Carbon\Carbon::now()->year }} CENRO SANTIAGO CITY. All rights reserved.</p>
    </footer>

    <main>
        <div class="map-container">
            <img src="data:image/png;base64,{{ $map }}" alt="Map" class="map-image">
        </div>

        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Barangay</th>
                    <th>Report Count</th>
                    <!-- Add more columns as necessary -->
                </tr>
            </thead>
            <tbody>
                @foreach ($reports as $report => $count)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $report }}</td>
                        <td>{{ $count }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </main>
    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script('
                $font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
                $pdf->text(270, 820, "Page $PAGE_NUM of $PAGE_COUNT", $font, 10);
            ');
        }
    </script>
</body>

</html>
