<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Users List</title>
    <style>
        body {
            font-family: 'Times New Roman', Times, serif;
            margin: 150px 20px 30px 20px;
        }

        @page {
            margin: 100px 30px;
            /* Top and Bottom margins leave space for header/footer */
        }

        header {
            position: fixed;
            top: -80px;
            /* Adjust position based on your header height */
            left: 0;
            right: 0;
            height: 80px;
            text-align: center;
            line-height: 1.5;
        }

        footer {
            position: fixed;
            bottom: -50px;
            /* Adjust position based on your footer height */
            left: 0;
            right: 0;
            height: 50px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }

        .footer-page {
            position: absolute;
            right: 0;
            bottom: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 14px;
        }

        table,
        th,
        td {
            border: 1px solid black;
        }

        th,
        td {
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #e6e6e6;
            text-transform: uppercase;
            font-size: 12px;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tr:nth-child(odd) {
            background-color: #fff;
        }
    </style>
</head>

<body>
    <header>
        <img src="{{ public_path('cenrologo.jpg') }}" alt="Government Logo" style="height: 100px;">
        <h1>Users List</h1>
        <p>Generated by the WMMNS</p>
        <p>Date: {{ \Carbon\Carbon::now()->format('F d, Y') }}</p>
    </header>
    <footer>
        <p>Certified by the CENRO SANTIAGO CITY</p>
        <p>&copy; {{ \Carbon\Carbon::now()->year }} CENRO SANTIAGO CITY. All rights reserved.</p>
    </footer>

    <main>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Full Name</th>
                    <th>Barangay</th>
                    <th>Email</th>
                    <th>Roles</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $user->firstname }} {{ $user->middlename }} {{ $user->lastname }}</td>
                        <td>{{ $user->barangay }}</td>
                        <td>{{ $user->email }}</td>
                        <td>
                            @foreach ($user->roles as $role)
                                <span>{{ $role->name }}</span>
                            @endforeach
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </main>

    <script type="text/php">
        if (isset($pdf)) {
            $pdf->page_script('
                $font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
                $pdf->text(270, 820, "Page $PAGE_NUM of $PAGE_COUNT", $font, 10);
            ');
        }
    </script>
</body>

</html>
